export const Banner = {
    ok : true,
    result : [
      { "image" : "https://grepp-programmers.s3.amazonaws.com/image/origin/production/banner/103631/b623de40-25ec-412b-9969-52455a3b0ec2.png", 
                  "link": "https://programmers.co.kr/pages/2021_edu_event_review?utm_source=programmers&utm_medium=banner&utm_campaign=review_event&utm_content=feb_review",
                   "id" : 1, },
      { "image" : "https://grepp-programmers.s3.amazonaws.com/image/origin/production/banner/110508/40845e11-42f9-4453-a429-3d259dfef140.png", 
                  "link": "https://programmers.co.kr/pages/2021-dev-survey?utm_source=programmers&utm_medium=banner&utm_campaign=survey_report-2021_challenges&utm_content=dev-2021",
                  "id" : 2, },
      { "image" : "https://grepp-programmers.s3.amazonaws.com/image/origin/production/banner/100824/7dd7d5db-677b-4a8a-8972-16c9cefe38f8.png", 
                  "link": "https://programmers.co.kr/learn/courses/11774?utm_source=programmers&utm_medium=banner&utm_campaign=learn&utm_content=course11774",
                  "id" : 3, },
      { "image" : "https://grepp-cloudfront.s3.ap-northeast-2.amazonaws.com/programmers_imgs/learn/banner/201209_course11190_banner.png", 
                  "link": "https://programmers.co.kr/learn/courses/11698?utm_source=programmers&utm_medium=banner&utm_campaign=learn&utm_content=course11698",
                  "id" : 4, },
      { "image" : "https://grepp-programmers.s3.amazonaws.com/image/origin/production/banner/113350/e7b48fb9-2790-47b8-8655-c33f5f6c2125.jpg", 
                  "link": "https://programmers.co.kr/competitions/1078/monthly-code-challenge-s2?utm_source=programmers&utm_medium=banner&utm_campaign=competition1078_challenges&utm_content=1078_img01",
                  "id" : 5, },
      { "image" : "https://grepp-cloudfront.s3.ap-northeast-2.amazonaws.com/programmers_imgs/learn/banner/201209_course11188_banner.png", 
                  "link": "https://programmers.co.kr/learn/courses/11710?utm_source=programmers&utm_medium=banner&utm_campaign=learn&utm_content=course11710",
                  "id" : 6, },
    ]
};

export const AlgorithmLists = {
  ok: true,
  total : 20,
  result: [
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
    {
      problem_id : 1,
      problem_name : "기능개발",
      problem_reference : "스택/큐",
      problem_solved : 19902,
      language : ["C++", "C#", "Go", "Java", "JavaScript", "Kotlin", "Python2", "Python3", "Ruby", "Scala", "Swift"],
    },
    {
      problem_id : 2,
      problem_name : "모든 레코드 조회하기",
      problem_reference : "SELECT",
      problem_solved : 27155,
      language : ["MySQL", "Oracle"],
    },
  ],
};

export const Level = {
  ok: true,
  result: ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"],
};

export const Language = {
  ok: true,
  result: [
    "C",
    "C++",
    "C#",
    "Go",
    "Java",
    "JavaScript",
    "Kotlin",
    "Python2",
    "Python3",
    "Ruby",
    "Scala",
    "Swift",
    "MySQL",
    "Oracle",
  ],
};

export const Reference = {
  ok: true,
  result: [
    "2021 KAKAO BLIND RECRUITMENT",
    "2020 KAKAO BLIND RECRUITMENT",
    "2019 KAKAO BLIND RECRUITMENT",
    "2018 KAKAO BLIND RECRUITMENT",
    "2019 카카오 개발자 겨울 인턴십",
    "2020 카카오 인턴십",
    "2017 카카오 예선",
    "2017 카카오코드 본선",
    "Summer/Winter Coding(~2018)",
    "Summer/Winter Coding(2019)",
    "월간 코드 챌린지 시즌 1",
    "찾아라 프로그래밍 마에스터",
    "2017 팁스타운",
  ],
};